Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,6 +4,7 @@ orbs:
   node: circleci/node@5.2.0
 
 jobs:
+  # Job to build the project and run tests
   build_and_test:
     machine:
       image: ubuntu-2204:2024.01.1
@@ -12,11 +13,13 @@ jobs:
       - node/install:
           node-version: '22.3'
       - run:
-          name: Install requirements
-          command: npm install
+          name: Install dependencies
+          command: npm ci
       - run:
           name: Run tests
-          command: npm run test
+          command: npm test
+
+  # Job to publish a canary version
   publish_canary:
     machine:
       image: ubuntu-2204:2024.01.1
@@ -25,19 +28,17 @@ jobs:
       - node/install:
           node-version: '22.3'
       - run:
-          name: Install requirements
-          command: npm install
+          name: Install dependencies
+          command: npm ci
       - run:
           name: Authenticate with NPM registry
-          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
+          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
       - run:
           name: Publish canary package
           command: |
-            npm publish --tag canary
-            if [ $? -ne 0 ]; then
-              echo "npm publish failed, stopping the job."
-              exit 1
-            fi
+            npm publish --tag canary || { echo "npm publish failed, stopping the job."; exit 1; }
+
+  # Job to validate the main version
   validate_main_version:
     machine:
       image: ubuntu-2204:2024.01.1
@@ -46,6 +47,8 @@ jobs:
       - run:
           name: Validate version
           command: ./bin/ci_validate_version.sh
+
+  # Job to publish the final package
   publish:
     machine:
       image: ubuntu-2204:2024.01.1
@@ -56,13 +59,14 @@ jobs:
           node-version: '22.3'
       - run:
           name: Authenticate with NPM registry
-          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
+          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
       - run:
-          name: Install requirements
-          command: npm install
+          name: Install dependencies
+          command: npm ci
       - run:
           name: Publish package
           command: npm publish
+
 workflows:
   CI:
     jobs:
